194.233.163.193 domain_name=swarm0.dyne.org country=DE
212.111.40.24 domain_name=swarm1.dyne.org country=FR
45.33.73.242 domain_name=swarm2.dyne.org country=IT
45.56.84.12 domain_name=swarm3.dyne.org country=ES
139.144.33.109 domain_name=swarm4.dyne.org country=IE
