---
- name: Deploy oracles
  hosts: all
  remote_user: root
  become: true
  become_user: zenswarm
  vars:
    repo: https://github.com/dyne/restroom-vmlet-template
    basepath: /zenswarm
    nodes: 5
    base_port: 25000
    public_base_port: 20000
    subs_file: subscriptions.csv
    country: DE
    announce_url: "http://did.dyne.org:12000/api/W3C-DID-controller-create-oracle-DID.chain "
    deannounce_url: "http://did.dyne.org:12000/api/W3C-DID-controller-remove-oracle"
    pubkeys: pubkeys.json
  tasks:
  - name: delete old logs
    file:
      path: "/home/zenswarm/.pm2/logs/"
      state: absent

  - name: Update packages of vmlet
    community.general.yarn:
      path: "{{ wd }}"
      state: latest
    loop: "{{ range(0, nodes) | list }}"
    vars:
      vmlet_name: "restroom-mw-{{ item }}"
      wd: "{{ basepath }}/vmlets/{{ vmlet_name }}"

  - name: Copy issuer pubkeys
    become: true
    copy:
      src: "{{ pubkeys }}"
      dest: "{{ wd }}/contracts"
    loop: "{{ range(0, nodes) | list }}"
    vars:
      vmlet_name: "restroom-mw-{{ item }}"
      wd: "{{ basepath }}/vmlets/{{ vmlet_name }}"

  - name: Set current nonce into redis
    become: true
    uri:
      url: https://did.dyne.org/api/zenswarm-issuer-set-nonce.chain
    run_once: true

  - name: Start oracles in pm2!
    command: pm2 start yarn --update-env --name {{ vmlet_name }} --time -- start
    args:
      chdir: "{{ wd }}"
    loop: "{{ range(0, nodes) | list }}"
    vars:
      vmlet_name: "restroom-mw-{{ item }}"
      wd: "{{ basepath }}/vmlets/{{ vmlet_name }}"
    loop_control:
      pause: 20


