---
- name: Deploy oracles
  hosts: all
  remote_user: root
  become: true
  become_user: zenswarm
  vars:
    repo: https://github.com/dyne/restroom-vmlet-template
    basepath: /zenswarm
    nodes: 5
    base_port: 25000
    public_base_port: 20000
    subs_file: subscriptions.csv
    country: DE
    announce_url: "http://did.dyne.org:12000/api/W3C-DID-controller-create-oracle-DID.chain "
    deannounce_url: "http://did.dyne.org:12000/api/W3C-DID-controller-remove-oracle"
  tasks:
  - name: Delete yarn.lock
    file:
      dest: "{{ basepath }}/yarn.lock"
      state: absent


  - name: Update packages of vmlet
    community.general.yarn:
      path: "{{ wd }}"
      state: latest
    loop: "{{ range(0, nodes) | list }}"
    vars:
      vmlet_name: "restroom-mw-{{ item }}"
      wd: "{{ basepath }}/vmlets/{{ vmlet_name }}"

